site:
  title: Sweet Tooth, a Clojure Single-Page App Framework
  url: https://sweettooth.dev
  start_page: overview::index.adoc
content:
  sources:
  - url: /Users/daniel/projects/web/sweet-tooth/documentation
    start_path: docs/overview
    branches: [master]
  - url: /Users/daniel/projects/web/sweet-tooth/documentation
    start_path: docs/quickstart
    branches: [master]
  - url: /Users/daniel/projects/web/sweet-tooth/endpoint
    start_path: docs
    branches: [master]
  - url: /Users/daniel/projects/web/sweet-tooth/todo-example
    start_path: docs
    branches: [master]
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: /Users/daniel/projects/web/sweet-tooth/documentation-ui/build/ui-bundle.zip
    # url: https://github.com/sweet-tooth-clojure/documentation-ui/raw/master/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true
